package py.com.sodep.mf.exchange.objects.error;

public enum ErrorType {

	SERVER_ERROR, APP_INVALID, APP_INACTIVE, APP_NOT_SELECTED, DEVICE_NOT_IN_APPLICATION, DEVICE_NOT_ASSOCIATED, LICENSE_EXPIRED, BAD_CREDENTIALS, NOT_MEMBER;

}
